### ISSUE TITLE
 base64 encoder mismatch 

### ISSUE THREAD

**Issue by xinlishang** [tripit/api#102]
In the website http://tripit.github.io/api/doc/v1/index.html, it shows demo example@example.com:secretpassword as the base64 encode with token: ZGVubWFya0B0cmlwaXQuY29tOnNlY3JldHBhc3N3b3Jk. However, I use other base64 encoder and found different result: ZXhhbXBsZUBleGFtcGxlLmNvbTpzZWNyZXRwYXNzd29yZA== 

Here is the external web: http://www.motobit.com/util/base64-decoder-encoder.asp and another one http://www.base64encode.org/

**Comment by tariqislam** [comment]
Hi,

I am assuming this was resolved since you posted OAuth issues that are further down the steps in OAuth1 registration. Please feel free to update this ticket with the solution you may have found, so that others in the future would be able to know the solution if they face a similar issue.

Thanks!

Tariq

**Comment by xinlishang** [comment]
Yes. this is resolved. By using Java binding code, I don't need to encode it by myself. It works. 

But the sample still shows descripency.

**Comment by xinlishang** [comment]
Yes. it was resolved. Sorry for late response. But the sample on your webpage still shows descripency. 

Date: Wed, 29 Jan 2014 09:54:07 -0800
