### ISSUE TITLE
Timezone for Note object

### ISSUE THREAD

**Issue by cpu8080** [tripit/api#146]
Hi,
We are currently implementing the Note obj API and setting the timezone to 'Pacific/Auckland'.

However the time is always expressed as AEST timezone. It seams the API does not observe the timezone value. 

Also do we need to populate the utc_offset node with a value?

Thanks

**Comment by hliss** [comment]
Hi @cpu8080, as noted in the XSD, time zones and UTC offsets are read-only fields in the API, which would explain the behavior you see! Best advice to set the time zone via the API right now would be to set a location for the note in NZ which would fall into the right timezone. UTC offset is actually output-only. We don't store and shouldn't accept that value since daylight savings or summer time can make this vary by location. Hope that helps!

I think we'll also investigate whether we can drop the read-only requirement for the time zone in the API, given it's settable on the web. Still, I'd advise the workaround above rather than waiting for this!

**Comment by cpu8080** [comment]
Thanks for the prompt response hliss. 
So all I have to do is populate the following nodes in the Address section ( address, city, country). 
Do I need to populate the latitude and longitude elements also?

Thanks

**Comment by hliss** [comment]
Nope, those are also read-only and will be ignored. They'll be set via the address or airport, etc.
