### ISSUE TITLE
Pagination support required for other endpoints

### ISSUE THREAD

**Issue by beaulebens** [tripit/api#147]
I've been using the API (and TripIt) for a while, and have been using the `https://api.tripit.com/v1/list/object/past/true/type/air` endpoint to get a detailed list of flights which have already been taken. This worked until recently, when the request started timing out, I assume because there's too much data to be included in the response.

I noticed that there are pagination parameters available (`page_num` and `page_size`), but that they're not supported for this specific type of request. It would be really helpful if they were supported, so that we could make requests like this without 1. requesting all data, ever (I only want recent/updated things), and 2. timing out.

Is this something that's likely to get any attention? Or is the API "frozen"/unsupported?

**Comment by hliss** [comment]
Hiya Beau, thanks for asking! We've also noticed this behavior and we do plan to start supporting pagination on such requests. Don't know an exact timeline offhand, but it's in the picture.

**Comment by beaulebens** [comment]
Hi @hliss, wondering if there's any movement on this one?

**Comment by hliss** [comment]
Hiya @beaulebens, I can say that indeed there is! Of course, once I say a timeline, something will happen to make me wrong. 

We're expecting pagination on `v1/list/object` requests to be available starting mid-next week, with enforced pagination to come in sometime after (to give developers enough time to update calls). If you're calling this API (and it looks like you are), you'll get an email when it's live. Only reason we haven't sent it out yet is because it'd be a pain to get an email describing something you can't yet develop against.

Hope that helps!

**Comment by beaulebens** [comment]
That's great news, I'll keep an eye out for an email and start looking at switching my client over to using paging.

**Comment by hliss** [comment]
Pagination support for `v1/list/object` is now live! Feel free to comment and reopen should you find any issues.
