### ISSUE TITLE
Where to set callback URL?

### ISSUE THREAD

**Issue by econchick** [tripit/api#155]
Hey folks -

Looking at the authentication docs, in step 2 to get the access token, it says that the callback URL:

> ... this parameter is optional if you associated a URL with your application when you registered it and obtained your OAuth consumer key and secret. 

However, I'm not seeing where I can set it where I've registered my app.  It's not the same URL as "URL where a user can learn about your application", is it?

Thanks!

**Comment by econchick** [comment]
Related - I am always getting "Access Request Failed" when trying to get user authorization, so I assume that it may have to do with the (lack of) callback url being set. Otherwise, not sure what's going on :-/

**Comment by hliss** [comment]
Hiya Lynn,

I think that part of the documentation is out of date. Thanks for pointing
it out!

You should provide a callback URL with your authorization redirect. "Access
Request Failed" most commonly refers to a missing callback URL; could also
be caused by an expired request token. Make sure the request token
presented with the authorization redirect is less than 5 minutes old.

Let us know if that doesn't help? Cheers!

-Harold

(edit: edited out mail context)

**Comment by econchick** [comment]
Ah thanks so much - got it to work; it was indeed the timing.

Unrelated question: using the python bindings you supplied, is there any way to request JSON response format?

**Comment by hliss** [comment]
Hi Lynn, at a glance, the bindings seem... older than our JSON support! It should be only a little bit of hacking the bindings to add the `format=json` query parameter to your requests (http://tripit.github.io/api/doc/v1/index.html#resource_section).
