### ISSUE TITLE
/list/object/format/json not returning any items

### ISSUE THREAD

**Issue by dougbradbury** [tripit/api#157]
This endpoint used to return all items whether they are in a trip or not and now I am just getting no results from this endpoint!

**Comment by hliss** [comment]
Hi Doug, is that the URL you're using? No parameters? Will look. Feel free to contact api-support@tripit.com with more specific info you wouldn't share in a public GitHub issue if you'd like!

**Comment by hliss** [comment]
Case solved over the api-support channel. Prior successful requests turned out to have been a fortunate bug! 

You can consult http://tripit.github.io/api/doc/v1/index.html#method_list for the parameters supported by the API. Please do reopen/create a new issue should you see any unexpected behavior!
