### ISSUE TITLE
504 Gateway Timeout

### ISSUE THREAD

**Issue by cdemyanovich** [tripit/api#205]
Starting on October 8th at about 12:40pm UTC, our API calls are returning a 504 Gateway Timeout.

Example endpoint: https://api.tripit.com/v1/list/object/traveler/false/format/json.

So far, we know of no changes on our end. Was there a change to the API that might be causing this issue?

Thank you for your help!

**Comment by cdemyanovich** [comment]
Following up on this after a long while. I'll add that I can reproduce this problem from my local machine:

```
curl -k -D /dev/tty --user <username>:<password> https://api.tripit.com/v1/list/object/traveler/false/format/json
HTTP/2 504
server: nginx
content-type: text/html
content-length: 176
date: Fri, 22 Dec 2017 15:43:18 GMT
set-cookie: lbsession=!+PlgugRtttQcgVgR2qJhjiH6jz4dJl+l2v0BiW/cs8Vj8rcfDMUI9/D5wJyWkaGvqlTZ9z63kCKTP7Y=; path=/; Httponly; Secure

<html>
<head><title>504 Gateway Time-out</title></head>
<body bgcolor="white">
<center><h1>504 Gateway Time-out</h1></center>
<hr><center>nginx</center>
</body>
</html>
```

**Comment by dave-symons** [comment]
Hi @cdemyanovich! Thank you for bringing this issue to our attention. I just tried your request using my personal account but unfortunately wasn't able to reproduce the issue.

```
$ curl -k -D /dev/tty --user <username>:<password> https://api.tripit.com/v1/list/object/traveler/false/format/json
HTTP/1.1 200 OK
Server: nginx
Content-Type: application/json
X-UA-Compatible: IE=Edge,chrome=1
Date: Fri, 22 Dec 2017 17:21:03 GMT
Content-Length: 2012
Connection: keep-alive
Set-Cookie: lbsession=<session_cookie>; path=/; Httponly; Secure

{"timestamp":"1513963263","num_bytes":"2096","NoteObject":{...}}
```

I think the next course of action would be to have our development team look at your account so we can figure out whats going on. Since this is a public forum I'm going to redirect you to our help page: 
https://help.tripit.com/hc/en-us/requests/new
Please fill this out and be sure to include the email of the account you're having issues with and we'll be happy to dig a little deeper to figure out whats going on.

Thanks!

**Comment by cdemyanovich** [comment]
@aosyborg Request submitted to Help Center. Thanks!

**Comment by cdemyanovich** [comment]
I accumulated so many trips in my account that API requests for travelers timed out. I'm working with the support team to remove trips.
