### ISSUE TITLE
Excel 2016 to web authorization successful but unable to get more

### ISSUE THREAD

**Issue by radit28** [tripit/api#229]
Hi, 

I am newbie in developing API and Web etc. But I really need data from trip it on excel for my team. 

I am currently using web for excel 2016, and I can connect and get data for this link https://api.tripit.com/v1/list/trip using my own username and password without encoded (because I am absolutely blank about it, But today I found there is a web to encode into base64 
https://www.url-encode-decode.com/base64-encode-decode/ -- will it be helpful? even so, I am quite not sure where to put Authorization: Basic xxxxx)

but it is not allow me to get data much more than list trip, while actually I need all the data including hotel, air booking etc. I tried to connect to https://api.tripit.com/v1/get/(id) but it showing up error. 

Is creating new application the only way to get all data from trip it? I tried to run Java that you mention on Java Binding but it is always failed. And to be honest, I am not sure which one should I run first. 

Your suggestion on tools that I should use to get all data excel file, I will really appreciated.

Thank you, 
Radit

**Comment by lundbrianh** [comment]
Hi Radit, 
It sounds like you might just need to include the `include_objects=true` query parameter to your `/v1/list/trip` request?  See the [endpoint documentation](http://tripit.github.io/api/doc/v1/index.html#method_list) for details on the request/response for that endpoint.  Alternatively, if you really want just the objects within a trip it may be preferable for you to use `https://api.tripit.com/v1/list/object`.  That endpoint supports the same authentication mechanism you used with `https://api.tripit.com/v1/list/trip.

It doesn't sound necessary to create an application for authenticating via OAuth.  However, your user would not have access to trip data created by another user without explicitly being granted access.  Perhaps this is the reason you're seeing an error calling `https://api.tripit.com/v1/get/(id)`?  If you have specific questions about the data you're getting back, please drop a line to support@tripit.com so that we can better address your individual needs privately. 

Hopefully that gets you a little closer, but please don't hesitate to reach back out with any additional questions.

**Comment by radit28** [comment]
Hi,

Thanks for getting back to answer my question. I did to connect to get all my data by add include_object/true .... but unfortunately, i still need to add another id if i want to get information in an different list trip. 

I tried to connect to this Https://api.tripit.com/v1/list/object, but it was failed. 

I'll getting back to you, once I tried it again. And I'll email you with the email address, with some confusion by the way since the support via apps (is it the same thing?) keep insisting me to contact their team in Gethub since it is related with the API. 

Anyway thanks,
Radit

**Comment by radit28** [comment]
HI, 

it is successful using this command. And I can get all the data I need. 

Https://api.tripit.com/v1/list/object

Now is another problem. 

Previously I tried it on my personal account. And now I want to create my friends account to be able to get the data. And again, I received the problem. I unable to go get data from https://api.tripit.com/v1/list/project by excel

How should I do?

Thanks, 
Dwi

**Comment by lundbrianh** [comment]
Hi @radit28 
Are you using the web authentication with the second user?  It might be the case that you just need that enabled for this other user?  To verify that please email api-support@tripit.com with a reference to this ticket and the primary email address on the user's account. 

Every user must be enabled to use web authentication.  If you are going to need to get data on behalf of many tripit users, you may be better served to setup an application with us, so those users can grant your application access to their data.  

To get started with an OAuth application, first head to https://www.tripit.com/developer to create your application and get your consumer's credentials.  Then, [refer to our OAuth authorization](http://tripit.github.io/api/doc/v1/index.html#oauth) documentation for a description of the steps that you would follow to generate and use access tokens.
