### ISSUE TITLE
Cannot roll new API secret

### ISSUE THREAD

**Issue by kgutwin** [tripit/api#273]
I'm hoping to find a solution to the problem in #270 and wanted to try to roll my API secret. When I click the "(roll)" link next to the API secret, I get a confirmation dialog that my app will need to be updated, but then end up being shown a 404 "page not found" message. The URL that the page is trying to send me is https://www.tripit.com/developer/updateApiSecret.

Can this feature be checked on? I don't seem to see any other way to update my API secret without requesting a new application, which will require my users to re-authorize. Thanks for your help!

**Comment by dssinger** [comment]
I just closed #270 - I had to change my copy of tripit.py to force the headers to include

User-Agent: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_4) AppleWebKit/603.1.30 (KHTML, like Gecko) Version/10.1 Safari/603.1.30'

because it appears the server was blacklisting the default User-Agent: python-urllib/3.9.

**Comment by hliss** [comment]
@kgutwin Rotating the secret was recently fixed; you should be able to do this now!
