### ISSUE TITLE
Notification API doesn't always send out notifications?

### ISSUE THREAD

**Issue by tijmenssmit80** [tripit/api#32]
I have been doing some test with the Notification API, and I noticed a few strange things. 

If I create a new trip, change the date once, or delete it, I recieve the notification.

But if I change the note for the trip (and don't change the date), or I try to change the dates more then once (I tried this with different trips), I never recieve a notification? 

Is this by design, or a bug? Or is there a temporary issue with the API itself? I first noticed this behavior yesterday, and I thought maybe just some server issues. But today is nothing different.

**Comment by tariqislam** [comment]
Hi,

The notification suppression functionality you see is by design: on the first edit on a trip or any of its trip items, a notification will be sent to your callback url. However, on subsequent changes to that trip for the immediate next 10 minutes, notifications are suppressed -- this is to prevent any flood of callbacks that may hit your server due to a large number of changes to a trip.

Please let me know if you have any other questions. Thanks.

Tariq

**Comment by tijmenssmit80** [comment]
That makes sense. But maybe this notification suppression should be added to the documentation? In the file for "TripIt API Documentation - v1 - Notification API" it's never mentioned. I spend quite a few hours yesterday trying to figure out what I was doing wrong, and why I never recieved all the notifcations that I expected to recieve when I made a change to a trip. Mentioning it in the documentation could save other people some time :)

**Comment by tariqislam** [comment]
Hi,

Definitely, I'll add it to the documentation. Thanks.

Tariq
