### ISSUE TITLE
problem with registered app domain

### ISSUE THREAD

**Issue by developer-arzion** [tripit/api#38]
Hello, I'm trying to use the "add-to-tripit" button in my application. The problem is that I have one secure purchase domain for multiple search domains. In the configuration page of the application I have registered a domain, and in the javascript code dynamically change domains, that did not work because they did not match with the registered domain.

**Comment by tariqislam** [comment]
Hi,

Currently we don't support wildcard matching for subdomains using a single Add-To-TripIt button. If you have multiple subdomains, at this point each would need to be registered for a separate Add-To-TripIt button. Please place the Add-To-TripIt JavaScript code on the subdomain that will be rendering the button for which you have registered, otherwise due to JS security concerns we do not render the button.

Please let me know if you have any other questions, or if you need to discuss this in more detail.

Thanks.

Tariq
