### ISSUE TITLE
DotNetOpenAuth & Tripit - Need User Info

### ISSUE THREAD

**Issue by ghost** [tripit/api#39]
Hello, 

I'm trying to use dotnetopenauth to log in to tripit however in the final stages I need to somehow understand what user I am connected to tripit with so as to associate that login with the consumer. Is this possible? Most implementations of openauth seem to have some kind of api hook that allows for a return of basic user info when passed access key - does tripit?

**Comment by tariqislam** [comment]
Hi,

I'm not sure I understand your question completely, but if you're asking whether we have an API call to get a user's profile info, here it is:

API Call: https://api.tripit.com/v1/get/profile
(http://tripit.github.com/api/doc/v1/index.html#method_get)

Please let me know if you have any other questions.

Tariq

**Comment by ghost** [comment]
I guess I phrased that pretty poorly - my apologies. What I'm looking for is a way to get information regarding the user who's access key it is that I am using. 

For instance, at the end of LinkedIn's OAuth process (http://developer.linkedin.com/documents/authentication) they call a certain profile URI with the access key and the user's information is returned. That way, the consuming application now knows who to associate a local account with. Otherwise, how do I know what ID to pass the profile GET to find the current user?

**Comment by tariqislam** [comment]
Hi,

You can get the user profile information in the API call I listed above. In addition, since we use OAuth, whenever you make a call against the API with a given user's OAuth credentials, you can only retrieve/send information pertaining to that given user. Hence there is no need to pass a user ID in our API.

As an example, when you make the call https://api.tripit.com/v1/get/profile, you only get profile information for the user whose OAuth token you are using. Similarly, https://api.tripit.com/v1/list/trip will only return the trips associated with that user.

Please let me know if you have any other questions.

Tariq
