### ISSUE TITLE
invalid token key 401

### ISSUE THREAD

**Issue by vikashkr** [tripit/api#59]
Please click here http://softoasistech.com/dev2013/tripit/new/

Click go Button

I get error 
Usage: api_url consumer_key consumer_secret access_token access_token_secret hereCreate a new test trip to New York: SimpleXMLElement Object ( [Error] => SimpleXMLElement Object ( [code] => 401 [detailed_error_code] => 106.100000 [description] => invalid token key: fdeee4dc249fc412b12789d9cb7ba33a851bd470 ) ) 

Please let me know solution

**Comment by tariqislam** [comment]
Hi,

I would need more information to help you out with this matter. Please send me an email at tariq@tripit.com with the following details:
- What language are you using, and are you using our provided API binding; if you are using our API binding, when did you last update it
- Your app's consumer key, and OAuth user token against which you are making API call
- Request url, OAuth signature string
- All request headers
- All response headers
- All response content
- When (date, time, timezone) the request was made (and error seen)
- How often does the API call fail
- Anything else that may help me debug

Thanks.

Tariq

**Comment by rose4jyoti** [comment]
Hi tariq,

Thanks for response. I am using PHP language.
I am using https://github.com/tripit/php_binding_v1 
I have pulled this last 15 days back from github

Apps Consumer key:392a516af25f755b535e37f44ec5568d0426b900
Apps Secret key:06e119adc35ebeeaab6e33b1ef97d9bdbd7ea1dc

Request Url:https://api.tripit.com

http://softoasistech.com/dev2013/tripit/new/

Request headers: https://www.tripit.com/oauth/authorize?oauth_token='.$request_token.'&oauth_callback=http://softoasistech.com/dev2013/tripit/new/example.php?token_secret='.$request_token_secret

Response :Usage: api_url consumer_key consumer_secret hereArray ( [oauth_token] => ced9b7e7b54ba17f9f002b1bdedca3cbf3321a6b [oauth_token_secret] => c980063d6b751ba2ff3f40ba4b3b6d3280ae1f1b ) 

When (date, time, timezone) the request was made (and error seen): any time checked it throws error

SimpleXMLElement Object ( [Error] => SimpleXMLElement Object ( [code] => 401 [detailed_error_code] => 106.100000 [description] => invalid token key: a60bda8b37b5086f3bae3537f7c746d3850a861d ) ) 

How often does the API call fail: always

Anything else that may help me debug: Open http://softoasistech.com/dev2013/tripit/new/  click go button

Thanks

**Comment by tariqislam** [comment]
Hi,

We had a bug that was fixed in the PHP binding roughly 15 days ago. Can you confirm that you are using the latest binding from Github?
A couple more questions:
- In your response, you have stated you get: 'Response :Usage: api_url consumer_key consumer_secret hereArray ( [oauth_token] => ced9b7e [oauth_token_secret] => c980063 )'
  Are you using the example.php script that comes with the binding? That script was written to be run from the command line, since it does not parse the GET parameters to extract the required OAuth credentials. Please look at te following issue: https://github.com/tripit/api/issues/44 which gives some details on how to start making calls with the PHP binding.

Thanks.

Tariq
