### ISSUE TITLE
retrieveRequestToken error 411

### ISSUE THREAD

**Issue by sheinkman** [tripit/api#60]
Hello,

I created a connection with tripit and it worked great for the last 3 years, about 2 weeks ago I cant retrieve request token.

when I run:
String authUrl = provider.retrieveRequestToken(consumer, OAuth.OUT_OF_BAND);

I get :
oauth.signpost.exception.OAuthCommunicationException: Communication with the service provider failed:
Server returned HTTP response code: 411 for URL: ttps://api.tripit.com/oauth/request_token

can you please point me to the right solution?

**Comment by tariqislam** [comment]
Hi,

I would need more information to help you out with this matter. Please send me an email at tariq@tripit.com with the following details:
- What language are you using, and are you using our provided API binding; if you are using our API binding, when did you last update it
- Your app's consumer key, and OAuth user token against which you are making API call
- Request url, OAuth signature string
- All request headers
- All response headers
- All response content
- When (date, time, timezone) the request was made (and error seen)
- How often does the API call fail
- Anything else that may help me debug

Thanks.

Tariq

**Comment by tariqislam** [comment]
Closing due to no response.

**Comment by sheinkman** [comment]
sorry was busy with another issue will send all the info to day

**Comment by tariqislam** [comment]
Hi,

Between step 2 and step 3 of the OAuth process, do you spend more than a
minute? The request token expires after a very short time.

Also, are you using our Java binding? If so, you can look at the source code
that is available (https://github.com/tripit/java_binding_v1).

Thanks.

## Tariq Islam

TripIt  |  Developer Advocate  |  1-415-401-1143

From:  sheinkman notifications@github.com
Reply-To:  tripit/api
<reply+i-12909417-5c3bd369e3b85908d4fd880dddacf918886d1079-1153782@reply.git
hub.com>
Date:  Sunday, April 21, 2013 12:28 AM
To:  tripit/api api@noreply.github.com
Cc:  Tariq Mohammed Islam tariq@tripit.com
Subject:  Re: [api] retrieveRequestToken error 411 (#60)

Hi Tariq, 

Sorry for the late replay, this is the 3rd part of the hand shake after I
allowed ATRIIS to change my tripit account.
It always return the unauthorized.

consumerKey = 2d862c1b7a6bad3194d6d8e353ad82800b13c35e

tripIt_endpoint= https://api.tripit.com/oauth/access_token

oauthToken=079e9b6c8bb0c1f148ec76506c3cbe39d82ce8d6

 oauthTokenSecret=23df78e46404a3e0e925f92438c0a9b62c866136

oauth_signature=4xvHcEa7nPyYlITyqFUfPmPHFvM%3D

authorization_header_string=OAuth
oauth_consumer_key="2d862c1b7a6bad3194d6d8e353ad82800b13c35e",oauth_signatur
e_method="HMAC-SHA1",oauth_timestamp="1366528651",oauth_nonce="88677e6d478c4
64c9ac9231c02598608",oauth_version="1.0",oauth_signature="4xvHcEa7nPyYlITyqF
UfPmPHFvM%3D",oauth_token="079e9b6c8bb0c1f148ec76506c3cbe39d82ce8d6",oauth_t
oken_secret="23df78e46404a3e0e925f92438c0a9b62c866136"

token=079e9b6c8bb0c1f148ec76506c3cbe39d82ce8d6

tokenSecret=23df78e46404a3e0e925f92438c0a9b62c866136

response content = response.getStatusLine()=HTTP/1.1 401 Unauthorized

another issue is when i use the java

OAuthProvider provider = new DefaultOAuthProvider(requestTokenUrl,
accessTokenUrl, authorizeUrl);
OAuthConsumer consumer;
consumer = new DefaultOAuthConsumer(consumerKey, consumerSecret);

with my consumerKey and consumerSecret i get http 411 error, I can't debug
this function because its not my jar file.

On Fri, Apr 12, 2013 at 12:17 AM, Tariq Islam
notifications@github.comwrote:

> Hi, 
> 
> I would need more information to help you out with this matter. Please
> send me an email at tariq@tripit.com with the following details:
> - Your app's consumer key, and OAuth user token against which you are
>   making API call
> - Request url, OAuth signature string
> - All request headers
> - All response headers
> - All response content
> - When (date, time, timezone) the request was made (and error seen)
> - How often does the API call fail
> - Anything else that may help me debug
> 
> Thanks. 
> 
> Tariq 
> 
> ‹ 
> Reply to this email directly or view it on
> GitHubhttps://github.com/tripit/api/issues/60#issuecomment-16261945
> . 

‹
Reply to this email directly or view it on GitHub
https://github.com/tripit/api/issues/60#issuecomment-16717232 .

**Comment by sheinkman** [comment]
Hi,

No the process is almost instant, and I used the example and get the 411 as
I mentioned.

Thanks
Sheinkman Uri

**Comment by tariqislam** [comment]
Hi Sheinkman,

I tested out the entire OAuth process and made a successful API call with your API credentials, and using the latest Java binding (https://github.com/tripit/java_binding_v1). I am unable to replicate your error. The two source files used to test this process (which are in the Java api binding) are OAuthAccessTokenGetter.java and CommandLineInterface.java. Please take a look at the testing output below:

```
15MBP-00631:java_binding_v1 tariqi$ java -cp tripit-api.jar:lib/* com.tripit.auth.OAuthAccessTokenGetter -key 2d862c1b7a6bad3194d6d8e353ad82800b13c35e -secret [CONSUMER_SECRET]

fetching unauthorized request token...
request token key: b24aa7efb9645025fd750f8ff3780f596c3bcebf
request token secret: 30f2211f86635e554fd9d2272c133fd8b056be87

now visit the following url and grant access to this application:
https://www.tripit.com/oauth/authorize?oauth_token=b24aa7efb9645025fd750f8ff3780f596c3bcebf&oauth_callback=https://www.tripit.com

enter the oauth_token value returned and hit ENTER when you're done:
b24aa7efb9645025fd750f8ff3780f596c3bcebf

fetching access token...
access token key: a2e6dbb8edb9b18db0df99eadc0bab6e411236bd
access token secret: 01816b2694f8b058937f24dd902f3978727deb6b

15MBP-00631:java_binding_v1 tariqi$ java -cp tripit-api.jar:lib/* com.tripit.api.CommandLineInterface -oauth 2d862c1b7a6bad3194d6d8e353ad82800b13c35e:[CONSUMER_SECRET]:a2e6dbb8edb9b18db0df99eadc0bab6e411236bd:01816b2694f8b058937f24dd902f3978727deb6b -action get:profile
RESPONSE CODE: 200 (OK)
RESPONSE TIME: 963ms
RESPONSE BODY: <Response><timestamp>1366924461</timestamp><num_bytes>1110</num_bytes><Profile ref… (truncated information)
```

Thanks.

Tariq

**Comment by sheinkman** [comment]
Hi Tariq,

I will try to test it again

Thanks
Uri

**Comment by sheinkman** [comment]
Hi Tariq,

I have tested it again and got the no results I didn't even  get the first
token this is the response I get:
 oauth.signpost.exception.OAuthCommunicationException: Communication with
the service provider failed: Server returned HTTP response code: 411 for
URL: https://api.tripit.com/oauth/request_token

maybe we are blocked in some way?
one of my concerns our IP may change between calls can that be a problem ?

Best Regards
Uri

**Comment by tariqislam** [comment]
Hi Uri,

I was finally able to replicate the issue, and we are working on a fix right now. Will let you know when it is working. Thank you very much for your patience!

Tariq

**Comment by sheinkman** [comment]
Thank you

**Comment by tariqislam** [comment]
Hi Uri,

I've updated the Java API binding in Github with the fix. Please let me know if you still have any issues.

Thanks.

Tariq

**Comment by sheinkman** [comment]
Thank you Tariq for solving the problem.

Uri
