### ISSUE TITLE
401 when testing rails 2 to rails 3 conversion

### ISSUE THREAD

**Issue by ndaskal** [tripit/api#76]
We have a rails 2 app that is working with tripit.  We are converting it to rails 3 and testing on a server with a different ip address and hostname.  The first attempt to connect to tripit fails getting  401 Unauthorized on request_token.get_access_token.
Is this something as simple as needing different consumer keys?

**Comment by tariqislam** [comment]
Hi,

I am assuming the Rails 3 testing server has a different hostname from the one you registered the callback url for your application? You may have to register for a different app if you want to do the testing on a different hostname.

Thanks.

Tariq

**Comment by ndaskal** [comment]
Hello Tariq,

Thank you for your response.  You are correct that the testing server has a different hostname from the server that is using the consumer key and secret in production.  How can we be certain that it is necessary to register a different app to test with a different hostname?  What is the process to register?  Thanks

**Comment by tariqislam** [comment]
Hi,

Actually you are correct, while we require a callback url during Step 2 when getting OAuth authorization for a user (see OAuth docs http://tripit.github.io/api/doc/v1/index.html#authentication_section) the obtaining of a request token should not need a callback, and is not really tied to a hostname/ip. Hence in essence if you repeat all OAuth steps to get a user's token on your testing server, using your production consumer key/secret, it should work. One guess I may have is that your testing server's clock is off perhaps? Otherwise without more details on the problem, I don't have any more guesses.

Thanks.

Tariq

**Comment by ndaskal** [comment]
The problem was apparently an incompatible level of the Ruby oauth gem.  Tariq, thanks for your help.  Now that I can successfully exchange oauth tokens I have another question which I will ask in a new "issue".
